feat: extend TripBloc with trip history functions
karhoo/web-lib-demand pull request #123
Opened 2021-01-26 13:34 UTC by Nick-Zag

2021-01-27 07:03 UTC, andrei-oksentyk commented on packages/demand-bloc-track-trip/src/TripBloc.ts
> +    const params = {
Looks like a "dirty hack". Could you explain your solution?

2021-02-01 08:43 UTC, andrei-oksentyk commented on packages/demand-bloc-track-trip/src/utils.ts
> +  }
`order_by` could contain other options of sorting (see [swagger](https://github.com/karhoo/api-v1-bookings/blob/818adaf772927457cbecf6ba8ccee839cc367dc5/docs/swagger/bookings.yaml#L1752)). I'd propose to define enum for it

2021-02-01 08:55 UTC, juliamaksimchik commented on packages/demand-bloc-track-trip/src/TripBloc.ts
> +      },
From my perspective, it's better to keep a single key not object

2021-02-01 08:55 UTC, juliamaksimchik commented on packages/demand-bloc-track-trip/src/TripBloc.ts
> +    return trips
`return response.body?.bookings || []`

2021-02-01 08:55 UTC, juliamaksimchik commented on packages/demand-bloc-track-trip/src/TripBloc.ts
> +    return trips
```
async searchTrips(
    statuses: TripStatuses[] = [],
    paginationOptions?: Pick<SearchParams, 'pagination_offset' | 'pagination_row_count'>
  ): Array<BookATripResponse>
```

2021-02-01 08:55 UTC, juliamaksimchik commented on packages/demand-bloc-track-trip/src/TripBloc.ts
> +  async searchTrips(
should it be private ?

2021-02-01 08:55 UTC, juliamaksimchik commented on packages/demand-bloc-track-trip/src/TripBloc.ts
> +        : [TripStatuses.COMPLETED]
ugh, don't really like this condition

2021-02-01 08:55 UTC, juliamaksimchik commented on packages/demand-bloc-track-trip/src/TripBloc.ts
> +    console.log('GET UPCOMING TRIPS BLOC')
pls remove

2021-02-01 08:55 UTC, juliamaksimchik commented on packages/demand-bloc-track-trip/src/TripBloc.ts
> +    console.log('GET PAST TRIPS BLOC')
pls remove

2021-02-01 08:55 UTC, juliamaksimchik commented on packages/demand-bloc-track-trip/src/TripBloc.ts
> +    console.log('GET NEXT PAST TRIPS BLOC')
pls remove

2021-02-01 09:24 UTC, aliaksandr-bordak commented on packages/demand-bloc-track-trip/src/TripBloc.ts
> +const defaultPastTripsRow = 10
I'd suggest to stick to the same code styling for constants, either `THIS_STYLE` or `thatStyle`

2021-02-01 09:24 UTC, aliaksandr-bordak commented on packages/demand-bloc-track-trip/src/TripBloc.ts
> +export type CustomOptions = {
Add an empty line before this line please

2021-02-01 09:24 UTC, aliaksandr-bordak commented on packages/demand-bloc-track-trip/src/TripBloc.ts
> +    this.options = options || {
Add an empty line before this line please

2021-02-01 09:24 UTC, aliaksandr-bordak commented on packages/demand-bloc-track-trip/src/utils.ts
> +    order_by: ['date'],
Might be good to create a constant for `'date'`

2021-02-01 09:29 UTC, aliaksandr-bordak commented on packages/demand-bloc-track-trip/src/TripBloc.ts
> +}
Is nesting really necessary here? I'd avoid nesting unless there are strong reasons for it.

2021-02-02 13:38 UTC, aliaksandr-bordak commented on packages/demand-bloc-track-trip/src/utils.ts
> +}
`return` is redundant here
```
... => ({
    trip_states: statuses,
    pagination_offset: paginationOptions?.pagination_offset || 0,
    pagination_row_count: paginationOptions?.pagination_row_count || 2,
    order_by: order || ['date'],
})
```

2021-02-02 14:56 UTC, juliamaksimchik approved these changes

2021-02-03 07:23 UTC, andrei-oksentyk approved these changes

2021-02-03 07:51 UTC, aliaksandr-bordak approved these changes

2021-02-03 09:08 UTC, aliaksandr-bordak requested changes
Rebase this branch because there are 3 tags missing: 15.1, 15.2, 15.3

2021-02-03 09:35 UTC, aliaksandr-bordak approved these changes

2021-02-03 09:37 UTC, merged